In [67]:
import numpy as np
import pandas as pd

- Import Dataset

In [68]:
Sales = pd.read_csv(r"D:\intenship\Sales_transactions_2022_2025.csv")
Sales

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18040,T02006253,O0106253,C03487,Ella Adams,32.0,Male,New Customer,2022-01-11,10:44:18,Online,...,Completed,Express,2.0,No,NaN,Emma Carter,MOM15,5.0,52.0,2022
18041,T02005688,O0102844,C00418,Jack Jones,32.0,Male,Returning Customer,2023-10-09,08:26:43,Retail Store,...,Processing,Standard,3.0,No,NaN,Emma Carter,SAVE10,4.0,107.0,2023
18042,T02011672,O0111672,C03311,Oscar Williams,37.0,Male,Corporate,2025-04-02,17:45:09,Online,...,Completed,Standard,6.0,No,NaN,Sophia Brown,SAVE10,2.0,58.0,2025
18043,T02013094,O0113094,C01590,Benjamin Moore,21.0,Female,New Customer,2022-06-08,15:03:38,Online,...,Completed,Standard,7.0,No,NaN,Noah Wilson,BLACKFRIDAY25,3.0,32.0,2022
18044,T02011617,O0111617,C01479,Lucas Allen,55.0,Male,Consumer,2025-06-30,19:01:38,Retail Store,...,Completed,Pickup,0.0,No,NaN,Grace Harris,NaN,5.0,73.0,2025

- Basic summary

In [94]:
Sales.shape

(18045, 24)

In [95]:
Sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18045 entries, 0 to 18044
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction_ID       18045 non-null  object
 1   Order_ID             18045 non-null  object
 2   Customer_ID          18045 non-null  object
 3   Customer_Name        18045 non-null  object
 4   Customer_Age         18045 non-null  Int64
 5   Customer_Gender      18045 non-null  object
 6   Customer_Segment     18045 non-null  object
 7   Order_Date           18045 non-null  datetime64[ns]
 8   Sales_Channel        18045 non-null  object
 9   Store_ID             18045 non-null  object
 10  Store_Name           18045 non-null  object
 11  Country              18045 non-null  object
 12  City                 18045 non-null  object
 13  Product_ID           18045 non-null  object
 14  Product_Name         18045 non-null  object
 15  Product_Category     18045 non-null  object
 16  Quantity             18045 non-null  int64
 17  Unit_Price           18045 non-null  float64
 18  Discount_Percentage  18045 non-null  float64
 19  Sales_Amount         18045 non-null  float64
 20  Cost_Amount          18045 non-null  float64
 21  Profit               18045 non-null  float64
 22  Payment_Method       18045 non-null  object
 23  Order_Status         18045 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(5), int64(1), object(16)
memory usage: 3.3+ MB

In [96]:
Sales.describe()

,Customer_Age,Order_Date,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit
count,18045.0,18045,18045.000000,18045.000000,18045.000000,18045.000000,18045.000000,18045.000000
mean,38.917927,2024-02-11 06:20:43.690773248,2.127127,232.685633,6.256858,457.309027,366.001156,91.404131
min,4.0,2022-01-01 00:00:00,-3.000000,21.390000,0.000000,16.680000,12.170000,-299.310000
25%,32.0,2023-02-13 00:00:00,1.000000,53.380000,0.000000,78.530000,56.120000,19.480000
50%,39.0,2024-02-07 00:00:00,2.000000,99.870000,5.000000,168.810000,122.300000,40.190000
75%,46.0,2025-02-13 00:00:00,3.000000,285.580000,10.000000,472.450000,376.020000,93.270000
max,112.0,2025-12-31 00:00:00,11.000000,1425.090000,110.000000,14303.070000,10791.000000,3512.080000
std,10.662362,NaN,1.786212,294.208022,6.881178,856.597181,705.866738,167.827883

# Cleaning Data

### Check Datatype

In [69]:
Sales.dtypes

Transaction_ID           object
Order_ID                 object
Customer_ID              object
Customer_Name            object
Customer_Age            float64
Customer_Gender          object
Customer_Segment         object
Order_Date               object
Order_Time               object
Sales_Channel            object
Store_ID                 object
Store_Name               object
Country                  object
Region                   object
City                     object
Product_ID               object
Product_Name             object
Product_Category         object
Product_Subcategory      object
Quantity                  int64
Unit_Price              float64
Discount_Percentage     float64
Sales_Amount            float64
Cost_Amount             float64
Profit                  float64
Payment_Method           object
Order_Status             object
Shipping_Method          object
Delivery_Days           float64
Return_Flag              object
Return_Reason            object
Sales_Representative     object
Promotion_Code           object
Customer_Rating         float64
Inventory_Level         float64
Order_Year                int64
dtype: object

In [70]:
Sales.columns

Index(['Transaction_ID', 'Order_ID', 'Customer_ID', 'Customer_Name',
       'Customer_Age', 'Customer_Gender', 'Customer_Segment', 'Order_Date',
       'Order_Time', 'Sales_Channel', 'Store_ID', 'Store_Name', 'Country',
       'Region', 'City', 'Product_ID', 'Product_Name', 'Product_Category',
       'Product_Subcategory', 'Quantity', 'Unit_Price', 'Discount_Percentage',
       'Sales_Amount', 'Cost_Amount', 'Profit', 'Payment_Method',
       'Order_Status', 'Shipping_Method', 'Delivery_Days', 'Return_Flag',
       'Return_Reason', 'Sales_Representative', 'Promotion_Code',
       'Customer_Rating', 'Inventory_Level', 'Order_Year'],
      dtype='object')

- Drop Unwanted Columns

In [71]:
Sales.drop(columns=["Inventory_Level","Promotion_Code"], inplace=True)

In [72]:
Sales.drop(columns=["Sales_Representative","Return_Reason"], inplace=True)

In [73]:
Sales.drop(columns=["Return_Flag","Delivery_Days"], inplace=True)

In [74]:
Sales.drop(columns=["Order_Year","Product_Subcategory"], inplace=True)

In [75]:
Sales.drop(columns=["Shipping_Method","Region"], inplace=True)

In [76]:
Sales.drop(columns=["Order_Time","Customer_Rating"], inplace=True)

In [77]:
Sales.columns

Index(['Transaction_ID', 'Order_ID', 'Customer_ID', 'Customer_Name',
       'Customer_Age', 'Customer_Gender', 'Customer_Segment', 'Order_Date',
       'Sales_Channel', 'Store_ID', 'Store_Name', 'Country', 'City',
       'Product_ID', 'Product_Name', 'Product_Category', 'Quantity',
       'Unit_Price', 'Discount_Percentage', 'Sales_Amount', 'Cost_Amount',
       'Profit', 'Payment_Method', 'Order_Status'],
      dtype='object')

- Change Data type

In [78]:
Sales["Order_Date"]=pd.to_datetime(Sales["Order_Date"],errors="coerce")

In [90]:
Sales["Customer_Age"]=Sales["Customer_Age"].astype("Int64")

In [91]:
Sales.dtypes

Transaction_ID                 object
Order_ID                       object
Customer_ID                    object
Customer_Name                  object
Customer_Age                    Int64
Customer_Gender                object
Customer_Segment               object
Order_Date             datetime64[ns]
Sales_Channel                  object
Store_ID                       object
Store_Name                     object
Country                        object
City                           object
Product_ID                     object
Product_Name                   object
Product_Category               object
Quantity                        int64
Unit_Price                    float64
Discount_Percentage           float64
Sales_Amount                  float64
Cost_Amount                   float64
Profit                        float64
Payment_Method                 object
Order_Status                   object
dtype: object

- Check duplicate and remove

In [ ]:
Sales.duplicated().sum()

In [92]:
Sales.drop_duplicates()

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Sales_Channel,Store_ID,...,Product_Name,Product_Category,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Payment_Method,Order_Status
0,T02016694,O0116694,C01482,Sophia Smith,28,Male,Consumer,2022-10-06,Online,LA-01,...,Webcam HD,Electronics,2,85.29,5.0,162.05,115.61,46.44,Credit Card,Completed
1,T02016374,O0108187,C01591,Hannah King,46,Female,Consumer,2024-06-03,Online,SYD-01,...,Office Keyboard,Electronics,6,58.85,15.0,300.13,237.00,63.13,Debit Card,Completed
2,T02004099,O0104099,C04140,Emma Wilson,42,Male,Consumer,2024-12-19,Online,PAR-01,...,Copy Paper Box,Office Supplies,2,43.92,15.0,74.66,73.17,1.49,Credit Card,Shipped
3,T02010280,O0110280,C03663,Daniel Clark,18,Male,Corporate,2025-10-05,B2B Portal,NYC-01,...,SmartDock USB-C,Electronics,11,115.34,15.0,1078.46,897.91,180.55,paypal,Completed
4,T02012685,O0112685,C02749,Sophia Smith,37,Male,Returning Customer,2022-09-13,B2B Portal,CHI-01,...,Desk Lamp,Furniture,4,69.71,15.0,237.03,164.95,72.08,Apple Pay,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18040,T02006253,O0106253,C03487,Ella Adams,32,Male,New Customer,2022-01-11,Online,SYD-01,...,Portable Heater,Appliances,1,93.25,0.0,93.25,66.55,26.70,Credit Card,Completed
18041,T02005688,O0102844,C00418,Jack Jones,32,Male,Returning Customer,2023-10-09,Retail Store,LON-01,...,AeroBook 14 Laptop,Electronics,2,901.65,5.0,1713.14,1401.99,311.15,Credit Card,Processing
18042,T02011672,O0111672,C03311,Oscar Williams,37,Male,Corporate,2025-04-02,Online,LON-01,...,Security Camera,Electronics,1,159.93,10.0,143.93,116.02,27.91,Apple Pay,Completed
18043,T02013094,O0113094,C01590,Benjamin Moore,21,Female,New Customer,2022-06-08,Online,COL-01,...,Notebook Pack,Office Supplies,2,27.20,0.0,54.41,32.71,21.70,Debit Card,Completed
18044,T02011617,O0111617,C01479,Lucas Allen,55,Male,Consumer,2025-06-30,Retail Store,TOR-01,...,Backup Drive 2TB,Electronics,1,139.31,0.0,139.31,102.21,37.10,PayPal,Completed

- Fill Null Values

In [81]:
Sales.isnull().sum()

Transaction_ID           0
Order_ID                 0
Customer_ID              0
Customer_Name          108
Customer_Age           218
Customer_Gender        162
Customer_Segment         0
Order_Date               0
Sales_Channel            0
Store_ID                 0
Store_Name               0
Country                  0
City                     0
Product_ID               0
Product_Name           144
Product_Category         0
Quantity                 0
Unit_Price               0
Discount_Percentage      0
Sales_Amount             0
Cost_Amount              0
Profit                   0
Payment_Method         147
Order_Status             0
dtype: int64

In [82]:
Sales["Customer_Age"]=Sales["Customer_Age"].fillna(Sales["Customer_Age"].median())

In [83]:
Sales["Payment_Method"]=Sales["Payment_Method"].fillna("Unknown")

In [85]:
Sales["Customer_Gender"]=Sales["Customer_Gender"].fillna(Sales["Customer_Gender"].mode())

In [88]:
Sales["Customer_Gender"]=Sales["Customer_Gender"].fillna("Unknown")

In [86]:
Sales["Product_Name"]=Sales["Product_Name"].fillna("Unknown Customer")
Sales["Customer_Name"]=Sales["Customer_Name"].fillna("Unknown Customer")

In [89]:
Sales.isnull().sum()

Transaction_ID         0
Order_ID               0
Customer_ID            0
Customer_Name          0
Customer_Age           0
Customer_Gender        0
Customer_Segment       0
Order_Date             0
Sales_Channel          0
Store_ID               0
Store_Name             0
Country                0
City                   0
Product_ID             0
Product_Name           0
Product_Category       0
Quantity               0
Unit_Price             0
Discount_Percentage    0
Sales_Amount           0
Cost_Amount            0
Profit                 0
Payment_Method         0
Order_Status           0
dtype: int64